### ISSUE TITLE
Crash on Binarization

### ISSUE THREAD

**Issue by vladvrabie** [unitbvcv/imageprocessingframework#10]
Current implementation of SmartDialog: if it can't cast the data from the text box to the requested type, it will send it as string. This includes sending empty string '' if the text box is empty.

If this wouldn't happen, the framework would crash because algorithms wouldn't receive their parameters.

If you press ok in the input dialog without entering anything, empty string is passed to the binarization algorithm as threshold and numpy throws exception.

Leave it like that?
Or surround the algorithm with try except?

**Comment by cosminpolifronie** [comment]
Is it possible to show a message box with an error when entering wrong type of parameters and stop the algorithm? Other validations shouldn't be done in the decorator and should be handled in the algorithm itself.

**Comment by vladvrabie** [comment]
Yes, will do
