### ISSUE TITLE
Remove warning from SmartDialog

### ISSUE THREAD

**Issue by vladvrabie** [unitbvcv/imageprocessingframework#5]
Warning message: QLayout: Attempting to add QLayout "" to SmartDialog "", which already has a layout

**Comment by cosminpolifronie** [comment]
Wait for #7 before trying to fix (you need to follow the steps shown there, but they crash the app for now).

**Comment by cosminpolifronie** [comment]
The warning appears when opening the thresholding algorithm (when displaying the input dialog).
